apiVersion: v1
kind: ConfigMap
metadata:
  name: cam-sim-conf
data:
  BOOTSTRAP_SERVER: wvi-kafka-bootstrap:9092
  TOPIC: windy-journey-images
  FPS: '0.1'
  CAMID: '0'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cam-sim
  labels:
    app: windy-journey
    app.kubernetes.io/part-of: windy-journey
spec:
  selector:
    matchLabels:
      app: cam-sim
  replicas: 1
  template:
    metadata:
      labels:
        app: cam-sim
    spec:
      containers:
        - name: cam-sim
          image: quay.io/wvi/cam-sim:1.0.0
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: cam-sim-conf
      restartPolicy: Always
