name: manuela_visual_inspection_ui
description: Dashboard for the end-to-end showcase of the Red Hat Data Science capabilities. Part of the MANUela Visual Inspection project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.1.1+2023061601

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  collection: ^1.17.0
  flutter_animate: ^4.1.1+1
  flutter_riverpod: ^2.3.2
  riverpod_annotation: ^2.0.2
  uuid: ^3.0.7
  socket_io_client: ^2.0.2
  go_router: ^7.1.1
  url_launcher: ^6.1.11
  line_icons: ^2.0.1
  package_info_plus: ^4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  build_runner: ^2.3.3
  riverpod_generator: ^2.1.4

flutter:
  uses-material-design: true

  assets:
    - assets/env/
    - assets/images/logos/
