apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  annotations:
    openshift.io/display-name: wjvi
    serving.kserve.io/deploymentMode: ModelMesh
    argocd.argoproj.io/sync-wave: "10"
  labels:
    name: wjvi
    opendatahub.io/dashboard: "true"
  name: wjvi
spec:
  predictor:
    model:
      modelFormat:
        name: onnx
        version: "1"
      runtime: wjvi
      storage:
        key: aws-connection-wjvi
        path: wjvi.onnx