apiVersion: batch/v1
kind: Job
metadata:
  name: create-infer-url-cm
  labels:
    app.kubernetes.io/part-of: windy-journey
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/sync-wave: "1"
spec:
  selector: {}
  template:
    spec:
      containers:
        - args:
            - -ec
            - |-
              INFER_URL=https://$(oc get route/model -o jsonpath={.spec.host})$(oc get route/model -o jsonpath={.spec.path})

              cat << EOF | oc apply -f-
              apiVersion: v1
              kind: ConfigMap
              metadata:
                name: image-processor-conf
              data:
                INFER_URL: "${INFER_URL}"
              EOF

              oc delete pods -l app=image-processor-00001
          command:
            - /bin/bash
          image: image-registry.openshift-image-registry.svc:5000/openshift/tools:latest
          imagePullPolicy: IfNotPresent
          name: create-infer-url-cm
      initContainers:
        - args:
            - -ec
            - |-
              echo -n 'Waiting for inference service route secret'
              while ! oc get route model 2>/dev/null | grep -qF model; do
              echo -n .
              sleep 5
              done; echo
          command:
            - /bin/bash
          image: image-registry.openshift-image-registry.svc:5000/openshift/tools:latest
          imagePullPolicy: IfNotPresent
          name: wait-for-inference-service-route
      restartPolicy: Never
      serviceAccount: demo-setup
      serviceAccountName: demo-setup