apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: windy-journey

resources:
  - sa-demo.yaml

  - secret-aws-connection.yaml

  - job-model-upload.yaml

  - serving-runtime.yaml
  - inference-service.yaml

  - job-infer-url.yaml
