kind: Secret
apiVersion: v1
metadata:
  name: aws-connection-wjvi
  labels:
    opendatahub.io/dashboard: 'true'
    opendatahub.io/managed: 'true'
  annotations:
    opendatahub.io/connection-type: s3
    openshift.io/display-name: wjvi
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-wave: "1"
stringData:
  AWS_ACCESS_KEY_ID: minio
  AWS_DEFAULT_REGION: us-east
  AWS_S3_BUCKET: wjvi
  AWS_S3_ENDPOINT: http://minio.windy-journey.svc.cluster.local:9000
  AWS_SECRET_ACCESS_KEY: minio123  
type: Opaque
