apiVersion: serving.kserve.io/v1alpha1
kind: ServingRuntime
metadata:
  annotations:
    enable-route: "true"
    argocd.argoproj.io/sync-wave: "5"
  labels:
    name: model-server-wjvi
    opendatahub.io/dashboard: "true"
  name: wjvi
spec:
  builtInAdapter:
    memBufferBytes: 134217728
    modelLoadingTimeoutMillis: 90000
    runtimeManagementPort: 8888
    serverType: ovms
  containers:
  - args:
    - --port=8001
    - --rest_port=8888
    - --config_path=/models/model_config_list.json
    - --file_system_poll_wait_seconds=0
    - --grpc_bind_address=127.0.0.1
    - --rest_bind_address=127.0.0.1
    image: registry.redhat.io/rhods/odh-openvino-servingruntime-rhel8@sha256:ff1a2fa6336793ecbf68aabac021df2fbe0f37e7c37675a17b92819b64b9abb4
    name: wjvi
    resources:
      limits:
        cpu: "2"
        memory: 8Gi
      requests:
        cpu: "1"
        memory: 4Gi
  grpcDataEndpoint: port:8001
  grpcEndpoint: port:8085
  multiModel: true
  protocolVersions:
  - grpc-v1
  replicas: 1
  supportedModelFormats:
  - autoSelect: true
    name: openvino_ir
    version: opset1
  - autoSelect: true
    name: onnx
    version: "1"
