apiVersion: v1
kind: Service
metadata:
  name: manuela-visual-inspection-ui
  namespace: manuela-visual-inspection-ui
  labels:
    app: manuela-visual-inspection-ui
    app.kubernetes.io/part-of: manuela-visual-inspection
spec:
  ipFamilies:
    - IPv4
  ports:
    - name: web
      protocol: TCP
      port: 8088
      targetPort: 8088
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: https
      protocol: TCP
      port: 443
      targetPort: 8443
  internalTrafficPolicy: Cluster
  type: ClusterIP
  ipFamilyPolicy: SingleStack
  sessionAffinity: None
  selector:
    app: manuela-visual-inspection-ui
