kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: dashboard-flutter-ui
  namespace: manuela-visual-inspection
  labels:
    app: manuela-visual-inspection-ui
    app.kubernetes.io/part-of: manuela-visual-inspection
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'manuela-visual-inspection-ui:latest'
  resources: {}
  successfulBuildsHistoryLimit: 3
  failedBuildsHistoryLimit: 3
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Containerfile
  postCommit: {}
  source:
    type: Git
    git:
      uri: 'https://github.com/Kounex/manuela-visual-inspection-ui'
  triggers:
    - type: ConfigChange
  runPolicy: Serial
