apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: windy-journey

bases:
  - ../../base

patchesJson6902:
  - target:
      version: v1
      kind: ConfigMap
      name: image-processor-conf
    patch: |-
      - op: replace
        path: /data/INFER_URL
<<<<<<< HEAD
        value: https://wvi-windy-journey.apps.cluster-mmcf2.sandbox3023.opentlc.com/v2/models/wvi/infer
=======
        value: https://wvi-windy-journey.apps.rosa-ptcdn.hguw.p1.openshiftapps.com/v2/models/wvi/infer
>>>>>>> 6999dcc0bfb33bc9b942aabfdf86529af912d2c4
