apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: windy-journey

bases:
  - ../../base

patchesJson6902:
  - target:
      version: v1
      kind: ConfigMap
      name: windy-journey-ui-config
    patch: |-
      - op: replace
        path: /data/config
<<<<<<< HEAD
        value: API_URL=http://windy-journey-backend-windy-journey.apps.cluster-mmcf2.sandbox3023.opentlc.com
=======
        value: API_URL=http://windy-journey-backend-windy-journey.apps.rosa-ptcdn.hguw.p1.openshiftapps.com
>>>>>>> 6999dcc0bfb33bc9b942aabfdf86529af912d2c4
