apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: manuela-visual-inspection

bases:
  - ../../base

patchesJson6902:
  - target:
      version: v1
      kind: ConfigMap
      name: manuela-visual-inspection-ui-config
    patch: |-
      - op: replace
        path: /data/config
        value: API_URL=manuela-visual-inspection-ui.apps.ocp5.stormshift.coe.muc.redhat.com
