apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: windy-journey

bases:
  - ../../base

patchesJson6902:
  - target:
      version: v1
      kind: ConfigMap
      name: windy-journey-ui-config
    patch: |-
      - op: replace
        path: /data/config
        value: API_URL=http://windy-journey-backend-windy-journey.apps.rosa-ptcdn.hguw.p1.openshiftapps.com
