apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: windy-journey

bases:
  - ../../base

patchesJson6902:
  - target:
      version: v1
      kind: ConfigMap
      name: windy-journey-ui-config
    patch: |-
      - op: replace
        path: /data/config
        value: BRAND_NAME=Windy Journey - Visual Inspection
  - target:
      version: v1
      kind: Route
      name: windy-journey-ui
    patch: |-
      - op: add
        path: /spec/
        value:
          tls:
            termination: edge
            insecureEdgeTerminationPolicy: Redirect
