apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: windy-journey

resources:
  - secret.yaml
  - service.yaml
  - pvc.yaml
  - deployment.yaml
  - route-api.yaml
  - route-console.yaml
