apiVersion: v1
kind: Secret
metadata:
  labels:
    app: minio
    app.kubernetes.io/component: minio
    app.kubernetes.io/instance: minio
    app.kubernetes.io/name: minio
    app.kubernetes.io/part-of: minio
    component: minio
  name: minio-root-user
type: Opaque
stringData:
    MINIO_ROOT_USER: minio
    MINIO_ROOT_PASSWORD: minio123