apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: windy-journey

bases:
  - ../../base

patchesJson6902:
  - target:
      version: v1
      kind: Route
      name: windy-journey-backend
    patch: |-
      - op: add
        path: /spec/tls
        value:
          termination: edge
          insecureEdgeTerminationPolicy: Redirect
