apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: manuela-visual-inspection

bases:
  - ../../base

patchesJson6902:
  - target:
      version: v1
      kind: Route
      name: manuela-visual-inspection-ui
    patch: |-
      - op: replace
        path: /spec/host
        value: manuela-visual-inspection-ui.apps.ocp5.stormshift.coe.muc.redhat.com
