apiVersion: v1
kind: ConfigMap
metadata:
  name: windy-journey-ui-config
  namespace: windy-journey-ui
  labels:
    app: windy-journey-ui
    app.kubernetes.io/part-of: windy-journey
data:
  config: >
    API_URL=http://windy-journey-backend-windy-journey.apps.ocp5.stormshift.coe.muc.redhat.com/
