kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: windy-journey-ui
  labels:
    app: windy-journey-ui
    app.kubernetes.io/part-of: windy-journey
spec:
  to:
    kind: Service
    name: windy-journey-ui
    weight: 100
  port:
    targetPort: http
  wildcardPolicy: None
