apiVersion: v1
kind: ServiceAccount
metadata:
  name: manuela-visual-inspection-ui
  namespace: manuela-visual-inspection-ui
  labels:
    app: manuela-visual-inspection-ui
    app.kubernetes.io/part-of: manuela-visual-inspection
